### ISSUE TITLE
Error setting workposition

### ISSUE THREAD

**Issue by Frenergy** [MetalWorkerTools/CNCL#6]
Hello,

I've uploaded GRBL-L to my Arduino Uno (no things yet connected, nor steppers, nor limit switches, etc). When connecting the Arduino in CNCL I get always the same bug:

Error Setting Workposition
Com Error Setting Workposition <X>
Check Your Positions
Controller will be disconnected

In GRBL info I saw this possible cause:
Last Error Command: G92X0 **_,_** 0000
Respons: error:1\r\n

Is it possible that the error is caused by the use of a comma instead of a period?

I've tried mulitple times, this error keeps occuring on all of my arduino's (also MEGA). I'm using Windows 11. Connection with UGS seems to be no problem.

![image](https://user-images.githubusercontent.com/105148264/208690609-16fd85dd-4926-44d2-bf71-102f950a3615.png)

**Comment by MetalWorkerTools** [comment]
Hello,I do not know if the dot/comma is a problem. I ca check this tomorrow.In your grbl info screen, I see a lot of com errors. I have had such a problem using WiFi and a (expensive) TP-Link router. I found that this router even timed out when sending a ping to a local IP-Adress. You could try connecting using USB to see if the problem persists.Huub In the grbl info screen, I see 70 coOp 20 dec. 2022 15:31 schreef Frenergy ***@***.***>:
Hello,
I've uploaded GRBL-L to my Arduino Uno (no things yet connected, nor steppers, nor limit switches, etc). When connecting the Arduino in CNCL I get always the same bug:
Error Setting Workposition
Com Error Setting Workposition 
Check Your Positions
Controller will be disconnected
In GRBL info I saw this possible cause:
Last Error Command: G92X0 , 0000
Respons: error:1\r\n
Is it possible that the error is caused by the use of a comma instead of a period?
I've tried mulitple times, this error keeps occuring on all of my arduino's (also MEGA). I'm using Windows 11. Connection with UGS seems to be no problem.


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
Op 20 dec. 2022 15:31 schreef Frenergy ***@***.***>:
Hello,
I've uploaded GRBL-L to my Arduino Uno (no things yet connected, nor steppers, nor limit switches, etc). When connecting the Arduino in CNCL I get always the same bug:
Error Setting Workposition
Com Error Setting Workposition 
Check Your Positions
Controller will be disconnected
In GRBL info I saw this possible cause:
Last Error Command: G92X0 , 0000
Respons: error:1\r\n
Is it possible that the error is caused by the use of a comma instead of a period?
I've tried mulitple times, this error keeps occuring on all of my arduino's (also MEGA). I'm using Windows 11. Connection with UGS seems to be no problem.


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
Op 20 dec. 2022 15:31 schreef Frenergy ***@***.***>:
Hello,
I've uploaded GRBL-L to my Arduino Uno (no things yet connected, nor steppers, nor limit switches, etc). When connecting the Arduino in CNCL I get always the same bug:
Error Setting Workposition
Com Error Setting Workposition 
Check Your Positions
Controller will be disconnected
In GRBL info I saw this possible cause:
Last Error Command: G92X0 , 0000
Respons: error:1\r\n
Is it possible that the error is caused by the use of a comma instead of a period?
I've tried mulitple times, this error keeps occuring on all of my arduino's (also MEGA). I'm using Windows 11. Connection with UGS seems to be no problem.

**Comment by Frenergy** [comment]
Hello Huub,

I've connected the arduino only via USB. The problem keeps occuring even when my internet connection is turned off. The amount of communication errors is due my endless attempt of trying to connect the arduino.

Looking forward to your investigation of the possible cause coming from the comma/period

Frédéric

**Comment by HuubBuis** [comment]
I have logged the connection of a USB (Mega) board.
`G92X1.7900
G92Z2.6000
G92Y-11.8950`
So there should be no comma but a dot.

The code for the G92 command
`string Command = String.Format("G92{0}{1:0.0000}", Axis, Position);`
Should produce a dot, not a comma.

I have checked de C# documentation and de decimal separator (.)  is so called Culture depended. So if the settings on your computer use a comma as decimal separator, the above code will produce a comma, not a dot.

I have to change the code so that is will produce a dot, independent of how the computer is setup. This is a bug that has been in the software from day one.

I will fix this today and upload a new version. It will probably take a few days because Microsoft has to verify the new code and it is holiday time.

A workaround is to setup your computer to use a dot as decimal separator. Beware, that could lead to problems when using other software.

Thanks for reporting this issue.

**Comment by HuubBuis** [comment]
I am puzzled why I have no problems on my PC(s). The PC is configured in the "nl-NL" language style and the decimal separator defaults to a comma (,). Whatever I change my Windows10 language and number notation to, it formats using de dot (.) as decimal separator. So I can't reproduce this error for testing.

I have changed the code so that (Gcode) numbers are formatted in the "nl-NL" language style.  In this style, I have changed the decimal separator to a dot (.)
I will upload this new version later this night after the  release documentation is done.

**Comment by Frenergy** [comment]
Hi Huub,

I've tried your suggestion and was able to make connect the arduino! Looking forward to test your software :)
BTW, I'm using the Belgian period keyboard layout (Flemish style). I was able to change my decimal separator via the control panel->Region->Additional settings

Could you please send me an email on frederic @ nlab . be ? I've a few questions and would like to collaborate to expand your GRBL-L version. My english is not really good, maar Nederlands is dus geen enkel probleem ;)

**Comment by HuubBuis** [comment]
Hi Frédéric,

Great to hear you have things working for you.
I have uploaded a new CNCL & CNCR version to the Microsoft store. Both versions also have some enhancements. Once Microsoft has completed the certification, I will let you know.

regards, Huub

**Comment by HuubBuis** [comment]
Hi Frédéric,

The new release is approved by Microsoft. It should be visible in the Microsoft store in a few hours. You can initiate an update using the Microsoft store to speed things up.

Regards, Huub
